// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgxsgvtkscjgyyubohri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZneHNndnRrc2NqZ3l5dWJvaHJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNDg4NzgsImV4cCI6MjA2NTYyNDg3OH0.N6fbgpY_ONgFU2p2z6xrCioe_kcA2pIn1uTUAhCv2to";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);